# Generated by Django 5.2.3 on 2025-07-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
